FROM python:2.7
RUN apt-get update && apt-get install -y python-pip

RUN pip install Pylons==0.9.7
RUN pip install SQLAlchemy==0.7.8 
RUN pip install textile==2.1.4 
RUN pip install FormBuild==2.2.0 
RUN pip install Elixir==0.7.1 
RUN pip install "Routes==1.12" 
RUN pip install "PyRSS2Gen" 
RUN pip install PasteScript
RUN pip install webob==1.0.8
RUN pip install pycurl
RUN pip install BeautifulSoup